version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    container_name: api_backend
    volumes:
      - ./backend:/code
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    container_name: frontend_react
  database:
    container_name: maria-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database-data:/var/lib/mysql
    expose:
      - "40000"
    ports:
      - "40000:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: db_mongo
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  database-data:
